export const mockUser = {
  id: "user_1",
  name: "John Doe",
  email: "demo@devstash.io",
  isPro: true,
};

export const mockItemTypes = [
  { id: "type_snippet", name: "snippet", icon: "Code", color: "#3b82f6", isSystem: true },
  { id: "type_prompt", name: "prompt", icon: "Sparkles", color: "#8b5cf6", isSystem: true },
  { id: "type_note", name: "note", icon: "StickyNote", color: "#fde047", isSystem: true },
  { id: "type_command", name: "command", icon: "Terminal", color: "#f97316", isSystem: true },
  { id: "type_file", name: "file", icon: "File", color: "#6b7280", isSystem: true },
  { id: "type_image", name: "image", icon: "Image", color: "#ec4899", isSystem: true },
  { id: "type_link", name: "link", icon: "Link", color: "#10b981", isSystem: true },
];

export const mockCollections = [
  {
    id: "col_1",
    name: "React Patterns",
    description: "Reusable React hooks, components, and patterns",
    isFavorite: true,
    createdAt: "2024-01-10T10:00:00Z",
    updatedAt: "2024-03-01T12:00:00Z",
  },
  {
    id: "col_2",
    name: "AI Prompts",
    description: "Prompts for code review, debugging, and documentation",
    isFavorite: false,
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-03-05T09:00:00Z",
  },
  {
    id: "col_3",
    name: "Dev Commands",
    description: "Useful CLI commands and terminal one-liners",
    isFavorite: true,
    createdAt: "2024-02-01T10:00:00Z",
    updatedAt: "2024-03-10T15:00:00Z",
  },
];

export const mockItems = [
  {
    id: "item_1",
    title: "useDebounce Hook",
    contentType: "text",
    content: "import { useState, useEffect } from 'react';\n\nexport function useDebounce<T>(value: T, delay: number): T {\n  const [debouncedValue, setDebouncedValue] = useState(value);\n\n  useEffect(() => {\n    const timer = setTimeout(() => setDebouncedValue(value), delay);\n    return () => clearTimeout(timer);\n  }, [value, delay]);\n\n  return debouncedValue;\n}",
    description: "A custom React hook for debouncing values.",
    typeId: "type_snippet",
    language: "typescript",
    isFavorite: true,
    isPinned: false,
    tags: ["react", "hooks", "typescript"],
    collectionIds: ["col_1"],
    createdAt: "2024-02-10T10:00:00Z",
    updatedAt: "2024-03-01T12:00:00Z",
  },
  {
    id: "item_2",
    title: "Code Review Prompt",
    contentType: "text",
    content: "Review the following code for bugs, performance issues, and best practices. Provide specific suggestions with examples.",
    description: "Comprehensive code review prompt for AI assistants.",
    typeId: "type_prompt",
    language: null,
    isFavorite: true,
    isPinned: false,
    tags: ["ai", "code-review", "prompts"],
    collectionIds: ["col_2"],
    createdAt: "2024-02-12T10:00:00Z",
    updatedAt: "2024-03-02T09:00:00Z",
  },
  {
    id: "item_3",
    title: "Git Undo Last Commit",
    contentType: "text",
    content: "git reset --soft HEAD~1",
    description: "Undo the last commit while keeping changes staged.",
    typeId: "type_command",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["git", "version-control"],
    collectionIds: ["col_3"],
    createdAt: "2024-02-15T10:00:00Z",
    updatedAt: "2024-03-03T11:00:00Z",
  },
  {
    id: "item_4",
    title: "Python List Comprehension Cheatsheet",
    contentType: "text",
    content: "# Basic\n[x for x in range(10)]\n\n# With condition\n[x for x in range(10) if x % 2 == 0]\n\n# Nested\n[x*y for x in range(5) for y in range(5)]",
    description: "Quick reference for Python list comprehensions.",
    typeId: "type_note",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["python", "cheatsheet"],
    collectionIds: [],
    createdAt: "2024-02-20T10:00:00Z",
    updatedAt: "2024-03-04T14:00:00Z",
  },
  {
    id: "item_5",
    title: "Vercel AI SDK Docs",
    contentType: "text",
    content: null,
    url: "https://sdk.vercel.ai/docs",
    description: "Official documentation for Vercel AI SDK.",
    typeId: "type_link",
    language: null,
    isFavorite: true,
    isPinned: false,
    tags: ["ai", "vercel", "docs"],
    collectionIds: ["col_2"],
    createdAt: "2024-02-22T10:00:00Z",
    updatedAt: "2024-03-05T09:00:00Z",
  },
  {
    id: "item_6",
    title: "tsconfig.json Template",
    contentType: "file",
    content: null,
    fileUrl: null,
    fileName: "tsconfig.json",
    fileSize: 512,
    description: "Standard TypeScript configuration for Next.js projects.",
    typeId: "type_file",
    language: "json",
    isFavorite: false,
    isPinned: false,
    tags: ["typescript", "config", "nextjs"],
    collectionIds: [],
    createdAt: "2024-02-25T10:00:00Z",
    updatedAt: "2024-03-06T10:00:00Z",
  },
  {
    id: "item_7",
    title: "useFetch Hook",
    contentType: "text",
    content: "export function useFetch<T>(url: string) {\n  const [data, setData] = useState<T | null>(null);\n  const [loading, setLoading] = useState(true);\n  const [error, setError] = useState<Error | null>(null);\n\n  useEffect(() => {\n    fetch(url)\n      .then(res => res.json())\n      .then(setData)\n      .catch(setError)\n      .finally(() => setLoading(false));\n  }, [url]);\n\n  return { data, loading, error };\n}",
    description: "Generic data fetching hook with loading and error states.",
    typeId: "type_snippet",
    language: "typescript",
    isFavorite: false,
    isPinned: true,
    tags: ["react", "hooks", "typescript"],
    collectionIds: ["col_1"],
    createdAt: "2024-03-01T10:00:00Z",
    updatedAt: "2024-03-07T12:00:00Z",
  },
  {
    id: "item_8",
    title: "Docker Prune All",
    contentType: "text",
    content: "docker system prune -a --volumes",
    description: "Remove all unused Docker containers, images, networks, and volumes.",
    typeId: "type_command",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["docker", "devops"],
    collectionIds: ["col_3"],
    createdAt: "2024-03-05T10:00:00Z",
    updatedAt: "2024-03-08T11:00:00Z",
  },
  {
    id: "item_9",
    title: "Explain This Code Prompt",
    contentType: "text",
    content: "Explain what the following code does in plain English. Break it down step by step and highlight any potential issues or improvements.",
    description: "Prompt for getting clear code explanations from AI.",
    typeId: "type_prompt",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["ai", "prompts", "learning"],
    collectionIds: ["col_2"],
    createdAt: "2024-03-08T10:00:00Z",
    updatedAt: "2024-03-09T09:00:00Z",
  },
  {
    id: "item_10",
    title: "useLocalStorage Hook",
    contentType: "text",
    content: "export function useLocalStorage<T>(key: string, initialValue: T) {\n  const [value, setValue] = useState<T>(() => {\n    try {\n      const item = window.localStorage.getItem(key);\n      return item ? JSON.parse(item) : initialValue;\n    } catch {\n      return initialValue;\n    }\n  });\n\n  const setStoredValue = (value: T) => {\n    setValue(value);\n    window.localStorage.setItem(key, JSON.stringify(value));\n  };\n\n  return [value, setStoredValue] as const;\n}",
    description: "Sync state with localStorage.",
    typeId: "type_snippet",
    language: "typescript",
    isFavorite: false,
    isPinned: false,
    tags: ["react", "hooks", "storage"],
    collectionIds: ["col_1"],
    createdAt: "2024-03-10T10:00:00Z",
    updatedAt: "2024-03-10T10:00:00Z",
  },
  {
    id: "item_11",
    title: "Project Architecture Diagram",
    contentType: "file",
    fileUrl: null,
    fileName: "architecture.png",
    fileSize: 204800,
    description: "High-level architecture diagram for the DevStash project.",
    typeId: "type_image",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["architecture", "docs"],
    collectionIds: [],
    createdAt: "2024-03-11T10:00:00Z",
    updatedAt: "2024-03-11T10:00:00Z",
  },
  {
    id: "item_12",
    title: "Tailwind CSS v4 Docs",
    contentType: "text",
    content: null,
    url: "https://tailwindcss.com/docs",
    description: "Official Tailwind CSS v4 documentation.",
    typeId: "type_link",
    language: null,
    isFavorite: false,
    isPinned: false,
    tags: ["tailwind", "css", "docs"],
    collectionIds: [],
    createdAt: "2024-03-12T10:00:00Z",
    updatedAt: "2024-03-12T10:00:00Z",
  },
];
